[package]
name = "mamba"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
memmap2 = "0.9.3"
rand = "0.8.5"
rayon = "1.8.1"
tokenizers = { version = "0.15.0", default-features = false, features = ["onig"] }
clap = { version = "4.2.4", features = ["derive"] }
